### PR TITLE
Update URLs and current sale status

### PR DESCRIPTION
**Pull request by mischah**
That’s it :octocat:

### CODE REVIEW

**Comment by mischah** [comment]
Hej,

please let me know if there is something additional I can do to get this merged.

Cheers, Michael

**Comment by mischah** [comment]
cc/ @voodootikigod @thefoxis @cramforce @janl ⬆️  😘

**Review by cramforce — APPROVED** [review]
Thanks!

**Comment by mischah** [comment]
Thank you.

**Pull request merged**
